{
    "swagger": "2.0",
    "info": {
        "version": "1.0.0",
        "title": "REST API GameVerse",
        "description": "<html><body>Esta es la documentación de la API para el sistema de Investigación Docencia.<p>Para poder usar esta API es necesario solicitar el token y con esto poder utilizar los servicios proporcionados.</p><br><p><b>Autenticación y token de API</b></p><p>La Universidad Tecnológica de la Mixteca (UTM) proporciona el api-token. Una vez que haya creado y confirmado su cuenta.</p></body></html>",
        "license": {
            "name": "MIT",
            "url": "https://opensource.org/licenses/MIT"
        }
    },
    "host": "localhost:3000",
    "basePath": "",
    "tags": [
        {
            "name": "Usuarios",
            "description": "API para obtener información de los usuarios de GameVerse"
        }
    ],
    "schemes": [
        "http"
    ],
    "consumes": [
        "application/json"
    ],
    "produces": [
        "application/json"
    ],
    "paths": {
        "/api/usuarios/mostrarTodosUsuarios": {
            "get": {
                "tags": [
                    "Usuarios"
                ],
                "summary": "Listado de todos los usuarios de GameVerse",
                "description": "<p>Servicio que devuelve la información completa de todas las cuentas de usuario creadas en la plataforma de GameVerse.</p>",
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": [
                                {
                                    "id": 1,
                                    "correo": "usuario@prueba.com",
                                    "password": "prueba",
                                    "nombre_usuario": "UsrPrueba",
                                    "nombre_comp": "Usuario de Prueba"
                                }
                            ]
                        },
                        "schema": {
                            "$ref": "#/definitions/Usuarios"
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/usuarios/mostrarUnUsuario/{id}": {
            "get": {
                "tags": [
                    "Usuarios"
                ],
                "summary": "Muestra los detalles de un único usuario.",
                "description": "<p>Servicio que devuelve los datos de la cuenta de usuario indicada por el identificador ingresado.</p>",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Identificador del usuario",
                        "required": true,
                        "default": 1
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": {
                                "id": 1,
                                "correo": "usuario@prueba.com",
                                "password": "prueba",
                                "nombre_usuario": "UsrPrueba",
                                "nombre_comp": "Usuario de Prueba"
                            }
                        },
                        "schema": {
                            "$ref": "#/definitions/Usuario"
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/usuarios/crearUsuario": {
            "post": {
                "tags": [
                    "Usuarios"
                ],
                "summary": "Creación de una cuenta nueva de usuario.",
                "description": "<p>Servicio que crea una nueva cuenta destinada a un usuario de GameVerse</p>",
                "operationId": "create",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "Usuario",
                        "in": "body",
                        "description": "Cuenta de usuario a crear",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/NuevoUsuario"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Usuario creado con éxito"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/usuarios/actualizarUsuario/{id}": {
            "put": {
                "tags": [
                    "Usuarios"
                ],
                "summary": "Edición de un usuario registrado previamente.",
                "description": "<p>Servicio que edita la cuenta de usuario indicada por el id de la URL</p>",
                "operationId": "update",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Identificador del usuario.",
                        "required": true,
                        "default": 1
                    },
                    {
                        "name": "Usuario",
                        "in": "body",
                        "description": "Datos del usuario.",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Usuario"
                        }
                    }
                ]
            }
        },
        "/api/usuarios/eliminarUsuario/{id}": {
            "delete": {
                "tags": [
                    "Usuarios"
                ],
                "summary": "Eliminación de un usuario registrada.",
                "description": "<p>Servicio que elimina definitivamente la cuenta de usuario indicada por el id de la URL.</p>",
                "operationId": "delete",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Identificador del usuario.",
                        "required": true,
                        "default": 1
                    }
                ]
            }
        },
        "/api/usuarios/validarUsuario":
        {
            "post":
            {
                "summary":"Inicia sesión en la tienda.",
                "description": "<p>Servicio que permite el inicio de sesión de un usuario en la tienda.</p><p>&nbsp;</p><p><em><strong>¿Como iniciar sesión en la tienda?</strong></em></p>",
                "produces":
                [
                    "application/json"
                ],
                "parameters":
                [
                    {
                        "name": "Usuario",
                        "in": "body",
                        "description": "Correo y contraseña del usuario que desea iniciar sesión.",
                        "required": true,
                        "schema":
                        {
                            "$ref" : "#/definitions/inicioSesion"
                        }
                    }
                ],
                "tags": ["Usuarios"],
                "responses":
                {
                    "201": {
                        "description": "OK",
                        "examples":{
                            "application/json":
                            [
                                {
                                    "id": 1,
                                    "correo": "usuario@prueba.com",
                                    "nombre_usuario": "UsrPrueba",
                                    "nombre_comp": "Usuario de Prueba",
                                    "is_admin" : 0
                                }
                            ]
                        },
                        "schema":{
                            "$ref": "#/definitions/usuarioLogueado"
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/usuarios/validarCorreoUsuario/{correo}":{
            "get": {
                "tags": ["Usuarios"],
                "summary": "Valida si el correo ya está registrado.",
                "description": "<p>Servicio que valida si el correo ingresado ya está registrado en la base de datos.</p>",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "correo",
                        "in": "path",
                        "description": "Correo del usuario.",
                        "required": true,
                        "default": "usuario@prueba.com"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Correo válido"
                    },
                    "403": {
                        "description": "Correo inválido"
                    }
                }
            }
<<<<<<< HEAD
=======
        },
        "/api/productos/crearProducto": {
            "post": {
                "tags": [
                    "Productos"
                ],
                "summary": "Registro de un producto nuevo.",
                "description": "<p>Servicio que registra un nuevo producto a ofrecerse en GameVerse, además de vincularlo con el administrador que realizó el proceso</p>",
                "operationId": "create",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "Producto",
                        "in": "body",
                        "description": "Producto a registrar, con el identificador del administrador que hizo el registro",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/NuevoProducto"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Producto registrado con éxito"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/productos/actualizarProducto/{id}": {
            "put": {
                "tags": [
                    "Productos"
                ],
                "summary": "Edición de un producto registrado previamente.",
                "description": "<p>Servicio que edita el producto indicado por el id de la URL</p>",
                "operationId": "update",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Identificador del producto.",
                        "required": true,
                        "default": 1
                    },
                    {
                        "name": "Producto",
                        "in": "body",
                        "description": "Datos del producto.",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Producto"
                        }
                    }
                ]
            }
        },
        "/api/productos/eliminarProducto/{id}": {
            "delete": {
                "tags": [
                    "Productos"
                ],
                "summary": "Eliminación de un producto registrado.",
                "description": "<p>Servicio que elimina definitivamente el producto indicado por el id de la URL, además de desvincularlo del administrador que lo registró originalmente.</p>",
                "operationId": "delete",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Identificador del producto.",
                        "required": true,
                        "default": 1
                    }
                ]
            }
        },
        "/api/administrador/mostrarTodosAdministradores": {
            "get": {
                "tags": [
                    "Administrador"
                ],
                "summary": "Listado de todos los Administradores de GameVerse",
                "description": "<p>Servicio que devuelve la información completa de todos los administradores creados en la plataforma de GameVerse.</p>",
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": [
                                {
                                    "id": 1,
                                    "correo": "admin@prueba.com",
                                    "password": "prueba",
                                    "nombre_usuario": "AdmPrueba",
                                    "nombre_comp": "Administrador de Prueba"
                                }
                            ]
                        },
                        "schema": {
                            "$ref": "#/definitions/Administradores"
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/administrador/mostrarUnAdministrador/{id}": {
            "get": {
                "tags": [
                    "Administrador"
                ],
                "summary": "Muestra los detalles de un único Administrador.",
                "description": "<p>Servicio que devuelve los datos de la cuenta de Administrador indicada por el identificador ingresado.</p>",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Identificador del Administrador",
                        "required": true,
                        "default": 1
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "examples": {
                            "application/json": {
                                "id": 1,
                                "correo": "admin@prueba.com",
                                "password": "prueba",
                                "nombre_usuario": "AdmPrueba",
                                "nombre_comp": "Administrador de Prueba"
                            }
                        },
                        "schema": {
                            "$ref": "#/definitions/Administrador"
                        }
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/administrador/crearAdministrador": {
            "post": {
                "tags": [
                    "Administrador"
                ],
                "summary": "Creación de una cuenta nueva de administrador.",
                "description": "<p>Servicio que crea una nueva cuenta destinada a un administrador de GameVerse</p>",
                "operationId": "create",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "Administrador",
                        "in": "body",
                        "description": "Cuenta de administrador a crear",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/NuevoAdministrador"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Administrador creado con éxito"
                    },
                    "403": {
                        "description": "Prohibido"
                    }
                }
            }
        },
        "/api/administrador/actualizarAdministrador/{id}": {
            "put": {
                "tags": [
                    "Administrador"
                ],
                "summary": "Edición de un administrador registrado previamente.",
                "description": "<p>Servicio que edita la cuenta de un administrador indicada por el id de la URL</p>",
                "operationId": "update",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Identificador del Administrador.",
                        "required": true,
                        "default": 1
                    },
                    {
                        "name": "Administrador",
                        "in": "body",
                        "description": "Datos del Administrador.",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Administrador"
                        }
                    }
                ]
            }
        },
        "/api/administrador/eliminarAdministrador/{id}": {
            "delete": {
                "tags": [
                    "Administrador"
                ],
                "summary": "Eliminación de un Administrador registrado.",
                "description": "<p>Servicio que elimina definitivamente la cuenta de un Administrador indicada por el id de la URL.</p>",
                "operationId": "delete",
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "name": "id",
                        "in": "path",
                        "description": "Identificador del Administrador.",
                        "required": true,
                        "default": 1
                    }
                ]
            }
>>>>>>> parent of 201ff05 (Merge remote-tracking branch 'origin/Fernando' into Frida)
        }
    },
    "definitions": {
        "Usuarios": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/Usuario"
            }
        },
        "Usuario": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "number",
                    "description": "Identificador único del usuario"
                },
                "correo": {
                    "type": "string",
                    "description": "Correo electrónico del usuario"
                },
                "password": {
                    "type": "string",
                    "description": "Contraseña del usuario"
                },
                "nombre_usuario": {
                    "type": "string",
                    "description": "Nombre de usuario elegido para la cuenta"
                },
                "nombre_comp": {
                    "type": "string",
                    "description": "Nombre completo del usuario"
                }
            }
        },
        "NuevoUsuario": {
            "type": "object",
            "properties": {
                "correo": {
                    "type": "string",
                    "description": "Correo electrónico del usuario"
                },
                "password": {
                    "type": "string",
                    "description": "Contraseña del usuario"
                },
                "nombre_usuario": {
                    "type": "string",
                    "description": "Nombre de usuario elegido para la cuenta"
                },
                "nombre_comp": {
                    "type": "string",
                    "description": "Nombre completo del usuario"
                }
            }
        },
        "inicioSesion":
        {
            "type": "object",
            "properties":
            {
                "correo":
                {
                    "type": "string",
                    "description": "Recibe el correo del usuario."
                },
                "contrasena":
                {
                    "type": "string",
                    "description": "Recibe la contraseña del usuario."
                }
            }
        },
        "usuarioLogueado":
        {
            "type": "object",
            "properties":
            {
                "id":
                {
                    "type": "number",
                    "description": "Guarda el id del usuario."
                },
                "correo":
                {
                    "type": "string",
                    "description": "Guarda el correo del usuario."
                },
                "nombre_usuario":
                {
                    "type": "string",
                    "description": "Guarda el nombre del usuario."
                },
                "nombre_comp":
                {
                    "type": "string",
                    "description": "Guarda el nombre completo del usuario."
                },
                "is_admin":
                {
                    "type": "number",
                    "description": "Identificador para saber si el usuario es administrador."
                }
            }
        }
    }
}